### ISSUE TITLE
Cannot find rule for token

### ISSUE THREAD

**Issue by schuemie** [sylvainhalle/Bullwinkle#5]
I am probably abusing Bullwinkle in several ways, but could use some guidance in how to do it right. 

I've converted the ANSI SQL BNF to what I think it the correct Bullwinkle syntax: [sql_bnf.txt](https://github.com/sylvainhalle/Bullwinkle/files/780613/sql_bnf.txt)

I then tried to parse some simple SQL:
```java
File file = new File("sql_bnf.txt");
try {
	BnfParser parser = new BnfParser(file);
	ParseNode node = parser.parse("SELECT * FROM my_table WHERE x = 5;");
} catch (InvalidGrammarException | IOException | ParseException e) {
	e.printStackTrace();
}
```
which results in this error message:
```
Cannot find rule for token <SQL_language_character>
	at ca.uqac.lif.bullwinkle.BnfParser.parse(BnfParser.java:483)
	at ca.uqac.lif.bullwinkle.BnfParser.parse(BnfParser.java:398)
	at org.ohdsi.parserTest.BullwinkleTest.main(BullwinkleTest.java:28)
```

I tried both the latest release (v1.3) as well as the current version in master, with no difference in results.

Help?

**Comment by sylvainhalle** [comment]
Hi Martijn,

First, thanks for your interest in Bullwinkle! I think the problem is that your BNF file uses `::=` instead of `:=` to separate the non-terminal symbol from its cases. Try that and let me know if this fixes your problem.

On a side note, I see that the grammar defines rules down to the level of single characters, for example to define the format of a valid identifier. BW was designed to parse whitespace-separated sequences of words, so I'm not sure this is a good fit for it. This could probably be better represented in Bullwinkle as a regex that defines the format of a particular word.

Best!

**Comment by schuemie** [comment]
Thanks! Changing `::=` to `:=` solved the error message, but now the parser produces a null object.

Now that I'm reading the instructions more thoroughly I see that Bullwinkle support only the basic BNF syntax, and not fancy things like optional elements `[]` and repetition `*` like mentioned [here](https://www.w3.org/Notation.html). I guess those are not on the development path for Bullwinkle?

**Comment by sylvainhalle** [comment]
Alas, not for now. However, none of these features is beyond the 
expressiveness of context-free grammars, so you should be able to write 
them, although in a slightly more involved way.

For example, in one of my projects, I wrote a list of elements as:

<list> := <element> | <list> , <element>

This should take care of repetition. And similarly, if I recall you can 
also use the `epsilon` symbol to say that something can parse to 
nothing, so this should allow you to handle optional elements.

In any case, I don't they these features would be hard to include in the 
tool, as the parsing algorithm is pretty straightforward. If you or 
someone you know would like to contribute, please feel free!

Best,

Sylvain

Martijn Schuemie wrote:
